bf16: true
cutoff_len: 16384
dataset: mixed_new_data_clean_large
deepspeed: deepspeed_config.json
do_sample: true
do_train: true
finetuning_type: full
ignore_data_skip: true
overwrite_output_dir: true
save_only_model: true
save_safetensors: true
gradient_accumulation_steps: 10
gradient_checkpointing: true
learning_rate: 0.00005
logging_steps: 1
lr_scheduler_type: cosine
mask_history: true
max_grad_norm: 0.5
max_new_tokens: 16384
resume_from_checkpoint: false
model_name_or_path: nvidia/OpenMath-Nemotron-1.5B
num_train_epochs: 3
output_dir: /storage/openpsi/models/nemotron_parallel_full_conclusion
per_device_train_batch_size: 1
save_steps: 500
save_strategy: steps
save_total_limit: 10
stage: sft
temperature: 0.7
template: default
top_p: 0.9
train_on_prompt: false
warmup_ratio: 0.05
weight_decay: 0.01
# ...existing code...
do_eval: false
eval_strategy: steps
eval_steps: 50
eval_dataset: eval_set_new
per_device_eval_batch_size: 1
# Correct wandb configuration for LLaMA-Factory
