# GitHub Labels Configuration
# This file defines labels for issue and PR management
# Apply with: gh label sync -f .github/labels.yml

# Difficulty Labels (for contributor guidance)
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers - beginner-friendly tasks"

- name: "easy"
  color: "c2e0c6"
  description: "Low complexity - suitable for new contributors"

- name: "medium"
  color: "fbca04"
  description: "Moderate complexity - some experience needed"

- name: "hard"
  color: "d93f0b"
  description: "High complexity - advanced knowledge required"

# Help & Engagement
- name: "help wanted"
  color: "008672"
  description: "Extra attention needed - community help appreciated"

- name: "beginner-friendly"
  color: "0e8a16"
  description: "Suitable for first-time contributors"

# Type Labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "enhancement"
  color: "84b6eb"
  description: "Improvement to existing feature"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "refactor"
  color: "e99695"
  description: "Code refactoring without changing functionality"

- name: "performance"
  color: "f9d0c4"
  description: "Performance improvement or optimization"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "discussion"
  color: "cc317c"
  description: "Discussion or RFC needed before implementation"

# Area Labels (component-specific)
- name: "area/engine"
  color: "5319e7"
  description: "Training or inference engine (FSDP, Megatron, vLLM, SGLang)"

- name: "area/workflow"
  color: "5319e7"
  description: "Rollout workflows and agent implementations"

- name: "area/algorithm"
  color: "5319e7"
  description: "RL algorithms (PPO, GRPO, RLOO, etc.)"

- name: "area/dataset"
  color: "5319e7"
  description: "Dataset loaders and processing"

- name: "area/reward"
  color: "5319e7"
  description: "Reward functions and evaluation"

- name: "area/docs"
  color: "5319e7"
  description: "Documentation (Jupyter Book, examples, guides)"

- name: "area/examples"
  color: "5319e7"
  description: "Example scripts and configurations"

- name: "area/ci"
  color: "5319e7"
  description: "CI/CD, testing infrastructure, GitHub Actions"

- name: "area/launcher"
  color: "5319e7"
  description: "Cluster launchers (Ray, Slurm, local)"

- name: "area/core"
  color: "5319e7"
  description: "Core APIs and infrastructure"

# Status Labels
- name: "needs-review"
  color: "ededed"
  description: "Waiting for code review"

- name: "needs-testing"
  color: "ededed"
  description: "Needs testing or test results"

- name: "blocked"
  color: "b60205"
  description: "Blocked by another issue or external dependency"

- name: "wip"
  color: "f9c513"
  description: "Work in progress - do not merge yet"

- name: "ready-to-merge"
  color: "0e8a16"
  description: "Approved and ready to merge"

# Priority Labels
- name: "priority/critical"
  color: "d93f0b"
  description: "Critical priority - needs immediate attention"

- name: "priority/high"
  color: "ff9900"
  description: "High priority"

- name: "priority/medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority/low"
  color: "c2e0c6"
  description: "Low priority"

# Special Labels
- name: "breaking-change"
  color: "b60205"
  description: "Introduces breaking changes to APIs or behavior"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right or is not reproducible"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "stale"
  color: "eeeeee"
  description: "No recent activity - may be closed soon"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

# Research & Experimental
- name: "research"
  color: "fef2c0"
  description: "Research-oriented feature or investigation"

- name: "experimental"
  color: "fff5b1"
  description: "Experimental feature - API may change"
