#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the AReaL project.
#

FROM quay.io/ascend/vllm-ascend:v0.14.0rc1-a3

ARG MEGATRON_TAG=core_v0.12.1
ARG MINDSPEED_TAG=v2.3.0_core_r0.12.1
ARG SGLANG_TAG=v0.5.7

# Update pip and install uv
RUN python3 -m pip install -U pip "setuptools>=77.0.3,<80" uv && \
    python3 -m pip install 'ray>=2.53.0' && \
    python3 -m pip cache purge

# Install Megatron & MindSpeed
RUN git clone --depth 1 --branch ${MEGATRON_TAG} https://github.com/NVIDIA/Megatron-LM.git /areal-workspace/Megatron-LM && \
    git clone --depth 1 --branch ${MINDSPEED_TAG} https://gitcode.com/Ascend/MindSpeed.git /areal-workspace/MindSpeed && \
    cp -r /areal-workspace/Megatron-LM/megatron /areal-workspace/MindSpeed/megatron && \
    python3 -m pip install -e /areal-workspace/MindSpeed --no-deps && \
    python3 -m pip install mbridge==0.15.1 && \
    python3 -m pip cache purge

# Install SGLang
RUN git clone --depth 1 --branch ${SGLANG_TAG} https://github.com/sgl-project/sglang.git /areal-workspace/sglang && \
    cd /areal-workspace/sglang && \
    mv python/pyproject_other.toml python/pyproject.toml && \
    pip install -e python[srt_npu] && \
    python3 -m pip cache purge

# Install AReaL dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv pip install -r pyproject.toml --system --extra npu --group dev

# Copy AReaL source code
COPY . /AReaL

# Install areal package in editable mode without dependencies
RUN uv pip install --no-deps -e /AReaL --system

# Add MindSpeed to PYTHONPATH as per official doc
ENV PYTHONPATH="/areal-workspace/MindSpeed:$PYTHONPATH"
