# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import router_pb2 as router__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in router_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBackend = channel.unary_unary(
                '/router.RouterManagement/AddBackend',
                request_serializer=router__pb2.AddBackendRequest.SerializeToString,
                response_deserializer=router__pb2.AddBackendResponse.FromString,
                _registered_method=True)
        self.DeleteBackend = channel.unary_unary(
                '/router.RouterManagement/DeleteBackend',
                request_serializer=router__pb2.DeleteBackendRequest.SerializeToString,
                response_deserializer=router__pb2.DeleteBackendResponse.FromString,
                _registered_method=True)
        self.ListBackends = channel.unary_unary(
                '/router.RouterManagement/ListBackends',
                request_serializer=router__pb2.ListBackendsRequest.SerializeToString,
                response_deserializer=router__pb2.ListBackendsResponse.FromString,
                _registered_method=True)
        self.PushStats = channel.unary_unary(
                '/router.RouterManagement/PushStats',
                request_serializer=router__pb2.PushStatsRequest.SerializeToString,
                response_deserializer=router__pb2.PushStatsResponse.FromString,
                _registered_method=True)


class RouterManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBackend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBackend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBackends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBackend': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBackend,
                    request_deserializer=router__pb2.AddBackendRequest.FromString,
                    response_serializer=router__pb2.AddBackendResponse.SerializeToString,
            ),
            'DeleteBackend': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBackend,
                    request_deserializer=router__pb2.DeleteBackendRequest.FromString,
                    response_serializer=router__pb2.DeleteBackendResponse.SerializeToString,
            ),
            'ListBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackends,
                    request_deserializer=router__pb2.ListBackendsRequest.FromString,
                    response_serializer=router__pb2.ListBackendsResponse.SerializeToString,
            ),
            'PushStats': grpc.unary_unary_rpc_method_handler(
                    servicer.PushStats,
                    request_deserializer=router__pb2.PushStatsRequest.FromString,
                    response_serializer=router__pb2.PushStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'router.RouterManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('router.RouterManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBackend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterManagement/AddBackend',
            router__pb2.AddBackendRequest.SerializeToString,
            router__pb2.AddBackendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBackend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterManagement/DeleteBackend',
            router__pb2.DeleteBackendRequest.SerializeToString,
            router__pb2.DeleteBackendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterManagement/ListBackends',
            router__pb2.ListBackendsRequest.SerializeToString,
            router__pb2.ListBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/router.RouterManagement/PushStats',
            router__pb2.PushStatsRequest.SerializeToString,
            router__pb2.PushStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
