experiment_name: gsm8k-grpo
trial_name: trial0

seed: 1
enable_offload: false
total_train_epochs: 10
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 1
  n_gpus_per_node: 8
  fileroot: /tmp/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve

allocation_mode: vllm:d4p1t1+d4p1t1

scheduler:
  type: null

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 256
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: false
  scheduling_spec: ${actor.scheduling_spec}
  use_lora: true

gconfig:
  n_samples: 4
  min_new_tokens: 0
  max_new_tokens: 1024
  greedy: false
  temperature: 1.0
  lora_name: "lora-gsm8k"

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ./model/Qwen3-0.6B
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer:
    type: adam
    lr: 1.70e-4
    weight_decay: 0.017
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  group_size: ${gconfig.n_samples}
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  dynamic_sampling: false
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  adv_norm:
    mean_level: batch
    std_level: batch
  max_new_tokens: ${gconfig.max_new_tokens}
  weight_update_mode: xccl

  # lora
  use_lora: ${rollout.use_lora}
  peft_type: lora
  # lora_rank: 32
  lora_rank: 16
  lora_alpha: 16
  target_modules: [all-linear]

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer: null
  scheduling_strategy:
    type: colocation
    target: actor
  scheduling_spec: ${actor.scheduling_spec}

# vLLM
vllm:
  model: ${actor.path}
  seed: ${seed}
  skip_tokenizer_init: false
  dtype: ${actor.dtype}
  max_model_len: 32768
  gpu_memory_utilization: 0.9
  # lora
  enable_lora: ${rollout.use_lora}
  lora_modules: '{"name": "${gconfig.lora_name}", "path": "./model/Qwen3.0.6B-16rank", "base_model_name": "${actor.path}"}'
  enforce_eager: true

# datasets
train_dataset:
  batch_size: 256
  shuffle: true
  pin_memory: true
  num_workers: 4
  path:  openai/gsm8k
  type: rl
  max_length: 1024

valid_dataset:
  batch_size: 256
  shuffle: true
  pin_memory: true
  num_workers: 4
  path:  openai/gsm8k
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled

perf_tracer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  enabled: false
  session_tracer:
    enabled: false

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 32768
  inference_server_env_vars: 'VLLM_USE_V1=1,TASK_QUEUE_ENABLE=2,HCCL_EXEC_TIMEOUT=14400,HCCL_OP_EXPANSION_MODE=HOST,VLLM_ALLOW_LONG_MAX_MODEL_LEN=1,ACL_DEVICE_SYNC_TIMEOUT=14400,HCCL_EVENT_TIMEOUT=14500,HCCL_ASYNC_ERROR_HANDLING=0,ACL_STREAM_TIMEOUT=14500000,HCCL_CONNECT_TIMEOUT=7200'
  trainer_env_vars: 'TASK_QUEUE_ENABLE=2,HCCL_EXEC_TIMEOUT=14400,HCCL_OP_EXPANSION_MODE=HOST,ACL_DEVICE_SYNC_TIMEOUT=14400,HCCL_EVENT_TIMEOUT=14500,HCCL_ASYNC_ERROR_HANDLING=0,ACL_STREAM_TIMEOUT=14500000,HCCL_CONNECT_TIMEOUT=7200,PYTORCH_NPU_ALLOC_CONF=expandable_segments:True'
  slurm:
    mount: /storage:/storage
    trainer_image: /storage/openpsi/images/areal-25.02-v0.3.0.post2-v3.sif
    inference_server_image: /storage/openpsi/images/areal-25.02-v0.3.0.post2-v3.sif


# launcher:
#   inference_server_cpus_per_gpu: 4
#   inference_server_mem_per_gpu: 32768
#   trainer_cpus_per_gpu: 4
#   trainer_mem_per_gpu: 32768
