name: areal-test-skypilot

resources:
  infra: gcp
  accelerators: A100:2
  autostop:
    idle_minutes: 10
    down: true
  cpus: 8+
  memory: 32GB+
  disk_size: 256GB
  image_id: docker:ghcr.io/inclusionai/areal-runtime:v0.3.4

num_nodes: 1

file_mounts:
  /storage: gs://areal-default

workdir: .

run: |
  python3 -m areal.launcher.local examples/math/gsm8k_grpo.py \
    --config examples/math/gsm8k_grpo.yaml \
    experiment_name=gsm8k-grpo \
    trial_name=trial0 \
    cluster.n_gpus_per_node=2 \
    allocation_mode=sglang.d1+d1 \
    train_dataset.batch_size=4 \
    actor.mb_spec.max_tokens_per_mb=4096
