experiment_name: infer-only
trial_name: trial0
allocation_mode: sglang.d6p1t1+d2p1t1
cluster:
  fileroot: /storage/openpsi/experiments
  n_nodes: 1
  n_gpus_per_node: 8
  name_resolve:
    type: nfs
    nfs_record_root: /storage/openpsi/name_resolve
seed: 1
total_train_epochs: 1
tokenizer_path: ${actor.path}
async_training: true

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 16
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: false

gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: 2048
  greedy: false
  temperature: 1.0

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /storage/openpsi/models/Qwen__Qwen2.5-3B-Instruct
  init_from_scratch: false
  disable_dropout: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 49152
  optimizer:
    type: adam
    lr: 2e-6
    gradient_clipping: 1.0
    lr_scheduler_type: cosine
    min_lr_ratio: 0.2
    warmup_steps_proportion: 0
  backend: fsdp

  group_size: ${gconfig.n_samples}
  eps_clip: 0.4
  reward_scaling: 1.0
  reward_bias: 0.0
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 49152
  optimizer: null
  backend: fsdp

sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  context_length: 32768
  mem_fraction_static: 0.8

train_dataset:
  batch_size: 16
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: /storage/openpsi/users/xmy/inclusionAI/AReaL/data/Werewolf_placeholder_3k.jsonl
  type: rl

saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 100
  freq_secs: 10800

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: 1
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: online

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 32768
