experiment_name: werewolf-grpo
trial_name: trial0
allocation_mode: sglang.d8p1t1+d8p1t2
cluster:
  fileroot: /storage/openpsi/experiments
  n_nodes: 3
  n_gpus_per_node: 8
  name_resolve:
    type: nfs
    nfs_record_root: /storage/openpsi/name_resolve
seed: 1
total_train_epochs: 1
tokenizer_path: ${actor.path}
async_training: true
opp_server_addrs: 33.180.160.33:16922,33.180.160.33:19176,33.180.160.33:25822,33.180.160.33:27625,33.180.160.33:31144,33.180.160.33:41656,33.180.160.33:47551
# opp_tokenizer_path: /storage/openpsi/models/Qwen__Qwen3-8B
# teacher_server_addrs: 33.180.162.249:16022,33.180.162.249:18157,33.180.162.249:25449,33.180.162.249:32136,33.180.162.249:37084,33.180.162.249:43790,33.180.162.249:46694 #t14b
# teacher_server_addrs: 33.180.160.212:11008,33.180.160.212:31199,33.180.160.212:34101,33.180.160.212:34794,33.180.160.212:42075,33.180.160.212:43070,33.180.160.212:47802 #t7b
# teacher_tokenizer_path: ""
role: villager

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 64
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 4
  enable_rollout_tracing: false

gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: 2048
  greedy: false
  temperature: 1.0

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  paths: null
  # path: /storage/openpsi/models/Qwen__Qwen2.5-7B-Instruct
  # path: /storage/openpsi/experiments/checkpoints/admin/xmy-werewolf-sppo-14/villager4-abl/default/epoch0epochstep59globalstep59
  # path: /storage/openpsi/experiments/checkpoints/admin/xmy-werewolf-sppo-14/villager4-t7b/default/epoch0epochstep59globalstep59
  path: /storage/openpsi/experiments/checkpoints/admin/xmy-werewolf-sppo-14/villager4-t14b/default/epoch0epochstep59globalstep59
  init_from_scratch: false
  disable_dropout: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer:
    type: adam
    # lr: 1e-6
    lr: 1e-20
    gradient_clipping: 1.0
    lr_scheduler_type: cosine
    min_lr_ratio: 0.6
    warmup_steps_proportion: 0
  backend: fsdp

  sft_reg: 1.5
  group_size: ${gconfig.n_samples}
  eps_clip: 0.4
  reward_scaling: 1.0
  reward_bias: 0.0
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer: null
  backend: fsdp

sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  context_length: 32768
  mem_fraction_static: 0.8

train_dataset:
  batch_size: 512
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: /storage/openpsi/users/xmy/inclusionAI/AReaL/data/Werewolf_placeholder_512.jsonl
  type: rl

saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 10
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: 1
  freq_secs: null

recover:
  mode: auto
  retries: 5
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: 10
  freq_secs: 3600

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: online

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 32768
  slurm:
    mount: /storage:/storage
    trainer_image: /storage/openpsi/images/sglang-v0.4.9.post2-cu126-v2.sif
    inference_server_image: /storage/openpsi/images/sglang-v0.4.9.post2-cu126-v2.sif
  trainer_env_vars: WANDB_API_KEY=local-667d8d7f101dad4eb9597d718d0c68f40e3792f9,WANDB_BASE_URL=http://8.150.1.98:8080
