bf16: true
cutoff_len: 2048
dataset: parallel_thinking
deepspeed: deepspeed_config.json
do_sample: true
do_train: true
finetuning_type: full
gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 1.0e-05
logging_steps: 5
lr_scheduler_type: cosine
mask_history: true
max_grad_norm: 0.5
max_new_tokens: 512
model_name_or_path: /home/zhangzy/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-7B/snapshots/916b56a44061fd5cd7d6a8fb632557ed4f724f60
num_train_epochs: 3
output_dir: /nvme0n1/zzy_model/saves_20250622_220612/deepseek-parallel-thinking
per_device_train_batch_size: 1
save_steps: 50
save_strategy: steps
save_total_limit: 10
stage: sft
temperature: 0.7
template: qwen
top_p: 0.9
train_on_prompt: false
warmup_ratio: 0.05
weight_decay: 0.01
