experiment_name: AVoyager-grpo
trial_name: trial1

seed: 1
total_train_epochs: 3
tokenizer_path: ${actor.path}
async_training: true

cluster:
  n_nodes: 1
  n_gpus_per_node: 8
  fileroot: /tmp/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve

allocation_mode: sglang.d4p1t1+d4p1t1

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 256
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 4
  enable_rollout_tracing: false

gconfig:
  n_samples: 1
  min_new_tokens: 0
  max_new_tokens: 30000
  greedy: false
  temperature: 1.0

actor:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path:  /storage/openpsi/models/Mini-o3-7B-SFT
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 32768
  optimizer:
    type: adam
    lr: 2e-6
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  backend: fsdp
  group_size: ${n_trajs}
  eps_clip: 0.4
  eps_clip_higher: 0.6
  c_clip: 2.0
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  behav_imp_weight_cap: 5.0
  dynamic_sampling: true
  overlong_reward_penalty: false
  overlong_tokens: 64
  overlong_penalty_factor: 1.0
  adv_norm:
    mean_level: group
    std_level: group
    group_size: ${n_trajs}
  max_new_tokens: ${gconfig.max_new_tokens}

ref:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 32768
  optimizer: null
  backend: fsdp

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: 64
  context_length: 32768
  mem_fraction_static: 0.8
  enable_multimodal: true

# datasets
train_dataset:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: [/storage/openpsi/data/VisualProbe_train/train.json, /storage/openpsi/data/DeepEyes_train_4K/train.json]
  type: rl

valid_dataset:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: [/storage/openpsi/data/VisualProbe_Easy/val.json, /storage/openpsi/data/VisualProbe_Medium/val.json, /storage/openpsi/data/VisualProbe_Hard/val.json, /storage/openpsi/data/Vstar_Bench/val.json]
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled
    project: qwen

launcher:
  inference_server_cpus_per_gpu: 4
  inference_server_mem_per_gpu: 32768
  trainer_cpus_per_gpu: 4
  trainer_mem_per_gpu: 32768

# AVoyager workflow settings
n_trajs: 4
