name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - arealite/**
  workflow_dispatch:

jobs:
  test-arealite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CI_NODE_ADDR }}
          username: ${{ secrets.CI_NODE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_path: scripts/run_test_arealite.sh
