name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - arealite/**
      - scripts/run_test_arealite.sh
  workflow_dispatch:

jobs:
  test-arealite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: appleboy/ssh-action@v1
        env:
          GIT_REPO: ${{ github.repository }}
          GIT_COMMIT_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.CI_NODE_ADDR }}
          username: ${{ secrets.CI_NODE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          envs: GIT_REPO,GIT_COMMIT_SHA
          script_path: scripts/run_test_arealite.sh
