name: Test AReaLite

on:
  pull_request:
    branches: [ lite ]
    paths:
      - .github/workflows/test-arealite.yml
      - arealite/**
      - ci/**
  workflow_dispatch:

jobs:
  test-arealite:
    environment:
      name: AReaLite-unittests
    runs-on: gpu
    steps:
      - uses: actions/checkout@v4

      - run: bash ./ci/test_arealite.sh
