name: Test AReaLite

on:
  pull_request:
    branches: [ lite ]
    paths:
      - .github/workflows/test-arealite.yml
      - arealite/**
      - ci/**
  push:
  workflow_dispatch:

jobs:
  test-arealite:
    environment:
      name: AReaLite-unittests
    runs-on: a800
    steps:
      - uses: actions/checkout@v4

      - run: bash ./ci/build_env_image.sh
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}

      - run: bash ./ci/test_arealite.sh
        env:
          GIT_COMMIT_SHA: ${{ github.sha }}
