name: Test AReaLite

on:
  pull_request:
    branches: [ lite ]
    paths:
      - .github/workflows/test-arealite.yml
      - arealite/**
      - ci/**
  workflow_dispatch:
  # 新增：监听PR review事件
  pull_request_review:
    types: [submitted]

jobs:
  # 新增：检查是否应该运行测试的job
  check-trigger:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'pull_request_review' && 
       contains(github.event.review.body, '/test') &&
       (github.event.review.author_association == 'OWNER' || 
        github.event.review.author_association == 'MEMBER' || 
        github.event.review.author_association == 'COLLABORATOR'))
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      pr_number: ${{ steps.check.outputs.pr_number }}
      pr_sha: ${{ steps.check.outputs.pr_sha }}
    steps:
      - name: Check if should run
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "pr_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "pr_number=" >> $GITHUB_OUTPUT
            echo "pr_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "pr_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  # 新增：为review触发的测试添加反应
  add-reaction:
    runs-on: ubuntu-latest
    needs: check-trigger
    if: github.event_name == 'pull_request_review' && needs.check-trigger.outputs.should_run == 'true'
    steps:
      - name: Add reaction to review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForPullRequestReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              review_id: context.payload.review.id,
              content: '+1'
            })

  test-arealite:
    runs-on: ubuntu-latest
    needs: check-trigger
    if: needs.check-trigger.outputs.should_run == 'true'
    concurrency:
      group: test-arealite-${{ needs.check-trigger.outputs.pr_number || github.run_id }}
    steps:
      - name: Get PR details
        id: pr-details
        if: github.event_name == 'pull_request_review'
        run: |
          # PR review事件中已经包含了PR信息
          echo "repo_url=${{ github.event.pull_request.head.repo.clone_url }}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_review'

      - uses: appleboy/ssh-action@v1
        env:
          GIT_REPO_URL: ${{ github.event_name == 'pull_request_review' && steps.pr-details.outputs.repo_url || format('https://github.bibk.top/{0}', github.repository) }}
          GIT_COMMIT_SHA: ${{ needs.check-trigger.outputs.pr_sha }}
          CI_NODE_SUDO_PW: ${{ secrets.CI_NODE_SUDO_PW }}
        with:
          host: ${{ secrets.CI_NODE_ADDR }}
          username: ${{ secrets.CI_NODE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          envs: GIT_REPO_URL,GIT_COMMIT_SHA,CI_NODE_SUDO_PW
          script_path: ci/clone_repo.sh

      - uses: appleboy/ssh-action@v1
        env:
          GIT_COMMIT_SHA: ${{ needs.check-trigger.outputs.pr_sha }}
        with:
          host: ${{ secrets.CI_NODE_ADDR }}
          username: ${{ secrets.CI_NODE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          command_timeout: 2h
          envs: GIT_COMMIT_SHA
          script_path: ci/build_env_image.sh

      - uses: appleboy/ssh-action@v1
        env:
          GIT_COMMIT_SHA: ${{ needs.check-trigger.outputs.pr_sha }}
        with:
          host: ${{ secrets.CI_NODE_ADDR }}
          username: ${{ secrets.CI_NODE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          command_timeout: 1h
          envs: GIT_COMMIT_SHA
          script_path: ci/test_arealite.sh

  # 新增：测试完成后更新PR状态
  update-pr-status:
    runs-on: ubuntu-latest
    needs: [check-trigger, test-arealite]
    if: always() && needs.check-trigger.outputs.should_run == 'true' && github.event_name == 'pull_request_review'
    steps:
      - name: Update PR with test results
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.check-trigger.outputs.pr_number }}
            });
            
            const testResult = '${{ needs.test-arealite.result }}';
            const emoji = testResult === 'success' ? '✅' : '❌';
            const status = testResult === 'success' ? 'passed' : 'failed';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.check-trigger.outputs.pr_number }},
              body: `${emoji} Tests **${status}** for commit ${pr.head.sha.substring(0, 7)}\n\n[View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`
            });